name: Discord Notify on PR Merge
on:
  pull_request:
    types: [closed]
jobs:
  notify:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Ilshidur/action-discord@master
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          args: "PR ${{ github.event.pull_request.number }} merged: ${{ github.event.pull_request.title }}"
